### ISSUE TITLE
Looging in with API key fails

### ISSUE THREAD

**Issue by digorgonzola** [IBM/actions-ibmcloud-cli#19]
Using this action with an API key fails with exit code 1:

```
The process '/usr/local/bin/ibmcloud' failed with exit code 1
```

Workflow:
```yaml
name: Workflow

on:
  pull_request:
    branches:
      - main

env:
  IBM_CLOUD_REGION: au-syd
  REGISTRY_HOSTNAME: au.icr.io
  REGISTRY_NAMESPACE: xxxxxxxx

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up ibmcloud CLI
        uses: IBM/actions-ibmcloud-cli@v1
        with:
          api_key: ${{ secrets.IBMCLOUD_API_KEY }}
          region: ${{ env.IBM_CLOUD_REGION }}
          group: default
          plugins: container-registry
```

**Comment by digorgonzola** [comment]
Manually logging in by adding the below step, works:
```yaml
      - name: Login to IBM Cloud
        run: |
          ibmcloud login --apikey ${{ secrets.IBM_CLOUD_API_KEY }} -r ${{ env.IBM_CLOUD_REGION }}
          ibmcloud cr login
```

**Comment by Fryguy** [comment]
I see the string you are using to reference the API key is different in each example.

```diff
+ secrets.IBMCLOUD_API_KEY
- secrets.IBM_CLOUD_API_KEY
```

**Comment by digorgonzola** [comment]
> I see the name you are using to reference the API key is different in each example.
> 
> + secrets.IBMCLOUD_API_KEY
> - secrets.IBM_CLOUD_API_KEY

Sorry. That's just a typo. It still fails with the correct secret.

```
| [command]/usr/local/bin/ibmcloud login -r us-south -g default
| API endpoint: https://cloud.ibm.com
| Logging in with API key from environment variable...
| Authenticating...
| FAILED
| Unable to authenticate
```

**Comment by Fryguy** [comment]
@digorgonzola Can you try the following as a manual login?  Asking because of 2 reasons. 1. we don't use the --apikey parameter, but instead use the ENV var and 2. we pass the group parameter

```yaml
      - name: Login to IBM Cloud
        env:
          IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }} 
        run: |
          ibmcloud login -r ${{ env.IBM_CLOUD_REGION }} -g default
          ibmcloud cr login
```
